
name: CI/CD Next.js Docker
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # === ЭТАП 1. Клонируем репозиторий ===
      - name: Checkout
        uses: actions/checkout@v3

      # === ЭТАП 2. Настраиваем Docker Buildx ===
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # === ЭТАП 3. Собираем образ ===
      - name: Build Docker image
        run: docker build --no-cache -t edons:latest . # run: docker build -t edons:latest .

      # === ЭТАП 4. Сохраняем образ в tar ===
      - name: Save Docker image as tar
        run: |
          docker save edons:latest -o edons.tar
          chmod 644 edons.tar  # Даем права на чтение всем

      # === ЭТАП 5. Копируем образ на сервер ===
      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.KLASTERWEB__SERVER_HOST }}
          username: ${{ secrets.KLASTERWEB__SERVER_USER }}
          key: ${{ secrets.KLASTERWEB__SERVER_SSH_KEY }}
          source: "edons.tar"
          target: "/var/www/edons_kz_usr/data/"

      # === ЭТАП 6. Разворачиваем на сервере через docker compose ===
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.KLASTERWEB__SERVER_HOST }}
          username: ${{ secrets.KLASTERWEB__SERVER_USER }}
          key: ${{ secrets.KLASTERWEB__SERVER_SSH_KEY }}
          script: |
            cd /var/www/edons_kz_usr/data/
            docker load -i edons.tar
            rm -r edons.tar
            docker compose -p edons down
            docker compose -p edons up -d --force-recreate --remove-orphans